services:
  lida-dev-box:    
    image: homeserv.uk/lida-base-image
    volumes:
      - "$LIDA_CLONE/app-configs:/usr/local/aspen-discovery/code/aspen_app/app-configs"
      - "./entrypoint.sh:/usr/local/aspen-discovery/code/aspen_app/entrypoint.sh"
    working_dir: "/usr/local/aspen-discovery/code/aspen_app"
    ports:
      - "8088:8081"
    container_name: containerlida
    platform: linux/x86_64
    tty: true
    stdin_open: true
    environment:
      - EXPO_USERNAME
      - EXPO_PASSWORD
      - QR_LINK
      - API_KEY_1
      - API_KEY_2
      - API_KEY_3
      - API_KEY_4
      - API_KEY_5
    command: /bin/sh -c " chmod +x ./entrypoint.sh && ./entrypoint.sh"
