services:
  lida-dev-box:    
    image: homeserv.uk/lida-base-image
    volumes:
      - "$LIDA_CLONE/app-configs:/usr/local/aspen-discovery/code/aspen_app/app-configs"
    working_dir: "/usr/local/aspen-discovery/code/aspen_app"
    ports:
      - "8088:8081"
    container_name: containerlida
    platform: linux/x86_64
    tty: true
    stdin_open: true
    environment:
      EXPO_USERNAME: 
      EXPO_PASSWORD: 
      QR_LINK:
    command: /bin/sh -c "export EXPO_PACKAGER_PROXY_URL=$QR_LINK; chmod +x ./start.sh && echo $EXPO_PASSWORD | npx expo login -u $EXPO_USERNAME  && ./start.sh"


      
