services:
  lida-dev-box:    
    image: homeserv.uk/lida-base-image
    volumes:
      - "$LIDA_CLONE/app-configs:/usr/local/aspen-discovery/code/aspen_app/app-configs"
      - "./entrypoint.sh:/usr/local/aspen-discovery/code/aspen_app/entrypoint.sh"
    working_dir: "/usr/local/aspen-discovery/code/aspen_app"
    networks:
      pihole_pihole_network:
    ports:
      - "8081:8081"
      - "80:80"
    container_name: containerlida
    platform: linux/x86_64
    tty: true
    stdin_open: true
    environment:
      - EXPO_USERNAME
      - EXPO_PASSWORD
      - QR_LINK
      - API_KEY_1
      - API_KEY_2
      - API_KEY_3
      - API_KEY_4
      - API_KEY_5
    command: /bin/sh -c " chmod +x ./entrypoint.sh && ./entrypoint.sh"

networks:
  pihole_pihole_network:
    external: true
  #   driver: macvlan
  #   driver_opts:
  #     parent: enp4s0
  #   ipam:
  #     config:
  #       - subnet: 192.168.0.0/24 #update if needed
  #         gateway: 192.168.0.1 #update if needed